version: '3.6'

services:
  # Watchtower constantly scans the CCAO registry and pulls new images
  # when found
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets/config.json:/config.json
    environment:
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_NO_RESTART=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_POLL_INTERVAL=1280
    restart: always
